# -*- coding: utf-8 -*-
"""Genetic_Algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQWYbk6akcZ-N21J6oGjGeVJIDEqc9Kc
"""

import random

csize=8
initpopsize=6
numOfgen=3

def genChrom():
    chrom=[]
    for i in range(csize):
        k=random.randint(0,8)
        chrom.append(k)

    return chrom
a=genChrom()
b=genChrom()
print('parent1',a)
print('parent2',b)

def cross(p1,p2):
    point = random.randint(3, 8)
    print('point',point)
    c1=p1[:point]+p2[point:]
    c2=p2[:point]+p1[point:]
    return c1,c2
c,d=cross(a,b)
print(c)
print(d)

def mutate(chrom):
    point = random.randint(0, 7)
    print('point',point)
    rval=random.randint(1,8)
    chrom[point]=rval
    return chrom

def fitness(chrom):
    count=0
    for p in range(8):
        for j in range(8):
            if chrom[p] == chrom[j]:
                count+=1
    return 28-count

population=[]
f=[]
for i in range(initpopsize):
    chrom=genChrom()
    f.append(fitness(chrom))
    population.append(chrom)



print('population',population)
print('fitnesses',f)

for i in range(numOfgen):
    newpop=[]
    while len(newpop)<6:
        t1=random.randint(0,5)
        t2=random.randint(0,5)
        p1=population[t1]
        p2=population[t2]
        c1,c2=cross(p1,p2)
        c1=mutate(c1)
        c2=mutate(c2)
        newpop.append(c1)
        newpop.append(c2)